#In this note book, we are going to cover some of the fundamentals concepts of TensorFlow

we are going to cover:

* Introduction to tensors
* Getting information from tensors
* Manupulating tensors
* Tensors & NumPy
* Using @tf.funtion()
* Using GPUs with TensorFlow
* some Exericses to try yourself 

Introduction to tensors

In [ ]:
#Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.8.0


In [ ]:
#Create tensors with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a Vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimensions of our vector
vector.ndim

1

In [ ]:
# Create a matrix (has more than one dimension)
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
another_matrix=tf.constant([[10.,7.],[3.,2.],[5.,6.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  6.]], dtype=float16)>

In [ ]:
another_matrix.ndim

2

In [ ]:
# Let's Create a tensor
tensor = tf.constant([[[1,2,3],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we created so far:

* Scalar: is a single number
* Vector: a number with direction (e.g windspeed and direction)
* Matrix: a 2-dimensional array of numers
* Tensor: a n-dimensional array of numers (where n can be any number, 0-dimensional tensor is a Saclar and 1-dimensional tensor is a vector)

# Creating Tensors with tf.variables 

In [ ]:
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor, unchangable_tensor


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

#Lets change the one of the element of changable tensor

In [ ]:
changable_tensor[0].assign(7)
changable_tensor


<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

#Creating Random tensors

In [ ]:
random_2= tf.random.Generator.from_seed(43)
random_2= random_2.normal(shape=(3,2))
random_3= tf.random.Generator.from_seed(43)
random_3= random_3.normal(shape=(3,2))

#Is random_2 and random_3 are equal?
random_2, random_3, random_2 == random_3

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.23193763, -1.8107855 ],
        [ 0.09988727, -0.50998646],
        [-0.7535805 , -0.57166284]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

## Shuffle the order of elements in a tensor

In [ ]:
#Shuffle a tensfor (valuable for when you want to shuffle your data so the inherent )
not_shuffled= tf.constant([[10,7],
                           [3,4],
                           [5,7]])
#Shuffle our not_shuffled tensor

tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [10,  7],
       [ 5,  7]], dtype=int32)>

In [ ]:
#tf.random.set_seed(42)....this is a global seed
tf.random.shuffle(not_shuffled,tf.random.set_seed(42))  #operational seed

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 3,  4],
       [ 5,  7],
       [10,  7]], dtype=int32)>

## Other ways to make tensors

In [ ]:
# create a tensor with all ones
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor with all zeros
tf.zeros(shape=(3,4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
#You can also turn NumPy arrays into tensors
#The Main difference between NumPy array and TensorFlow tensor is, tensors can be run on GPU and much faster to computing
import numpy as np
numpy_A = np.arange(1,25,dtype=np.int32) # create a numpy array between 1 and 15
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A =tf.constant(numpy_A,shape=(2,3,4))
B= tf.constant(numpy_A, shape=(4,6))
C= tf.constant(numpy_A)
A,B,C

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

## Getting more information from our tensors
* Shape ...tensor.shape
* Rank.....tensor.ndim
* Axis or Dimension......tensor[0]
* Size......tf.size(tensor)


In [ ]:
# Create a rank 4 tesor( 4 dimesions)
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor.shape, rank_4_tensor.ndim, rank_4_tensor[0],tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]),
 4,
 <tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
#Get various attributes of our tensor
print("data type of every element:", rank_4_tensor.dtype)
print("Number of dimension (rank): ", rank_4_tensor.ndim)
print("Shape of the tensor: ", rank_4_tensor.shape)
print("Element along the 0 axis : ", rank_4_tensor.shape[0])
print("Element along the last axis : ", rank_4_tensor.shape[-1])
print("Total number of elements of out tensor : ", tf.size(rank_4_tensor))
print("Total number of elements of out tensor : ", tf.size(rank_4_tensor).numpy())

data type of every element: <dtype: 'float32'>
Number of dimension (rank):  4
Shape of the tensor:  (2, 3, 4, 5)
Element along the 0 axis :  2
Element along the last axis :  5
Total number of elements of out tensor :  tf.Tensor(120, shape=(), dtype=int32)
Total number of elements of out tensor :  120


## Indexing tensors
tensors can be indexed just like python list

In [ ]:
# get the first 2 elements of each dimension
rank_4_tensor[:2,:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# get the first element of each dimension from each index except for last one
rank_4_tensor[:1,:1,:1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:,:,:1]

<tf.Tensor: shape=(1, 3, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]],

        [[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# create a rank 2 tensor
rank_2_tensor=tf.constant([[2,3],
                           [4,5]])
rank_2_tensor.shape, rank_2_tensor.ndim, 

(TensorShape([2, 2]), 2)

In [ ]:
# get the last item of each row of the rank 2 tesor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([3, 5], dtype=int32)>

In [ ]:
#Add extra dimension to our rank 2 tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=-1) # "-1" means expands final axis 

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [3]],

       [[4],
        [5]]], dtype=int32)>

In [ ]:
# alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis=0) 

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[2, 3],
        [4, 5]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[2, 3]],

       [[4, 5]]], dtype=int32)>

## Manupulating tensors (tensor operations)

* Basic operations:

 **'+', '-', '*', '/'**

In [ ]:
# add values to a tensor using addition operator
tensor = tf.constant([[10,7],
                      [3,4]])
tensor + 7

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 14],
       [10, 11]], dtype=int32)>

In [ ]:
tensor *3

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 21],
       [ 9, 12]], dtype=int32)>

In [ ]:
tensor -2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[8, 5],
       [1, 2]], dtype=int32)>

In [ ]:
#tensor =tensor +2
#tensor

In [ ]:
#we can also use TensorFlow built-in funtions
tf.add(tensor,3)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[13, 10],
       [ 6,  7]], dtype=int32)>

In [ ]:
tf.multiply(tensor,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 14],
       [ 6,  8]], dtype=int32)>

**Metrix Multiplecation**

* In the Machine learning, metrix multiplecation is one of the most common tensor operations 

* There are two rules to fulfill to do a metrix multiplecation of two tensors:

1.The inner dimensions must match

2.The resulting matrix has the same shape of the outer dimension 

* Generally, when we performaning martix multiplecation we will use "trasnpose" (rather than ...reshape)to satisfy matrix multiplecation rules. 

In [ ]:
# Metrix Multiplecation in TensorFlow

print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
tensor, tensor

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>, <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[10,  7],
        [ 3,  4]], dtype=int32)>)

In [ ]:
tensor*tensor # multiplying two tensors are not same as Metrix Multiplecation

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [ ]:
# Metrix Multiplecation with python operator "@"
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
#Create a tensor(3,2) tensor
X=tf.constant([[2,5],
              [6,7],
               [1,8]])


#Create a tensor(3,2) tensor
Y=tf.constant([[1,2],
               [2,3],
               [3,2]])

Z=tf.reshape(Y,shape=(2,3))
print(Z)
#Reshape Y tensor
#try to matrix multiple tensors of same shape
#now the inner dimesions are matching...X(3,2)..Y(2,3)
print("matrix multiple tensors of same shape")
X @ tf.reshape(Y,shape=(2,3))

tf.Tensor(
[[1 2 2]
 [3 3 2]], shape=(2, 3), dtype=int32)
matrix multiple tensors of same shape


<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 19, 14],
       [27, 33, 26],
       [25, 26, 18]], dtype=int32)>

In [ ]:
#we can also change the shape of tesnor using transpose

X, tf.transpose(X), tf.reshape(X,shape=(2,3))

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 6, 1],
        [5, 7, 8]], dtype=int32)>, <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[2, 5, 6],
        [7, 1, 8]], dtype=int32)>)

In [ ]:
#Try metrix multiplecation using tf.transpose
tf.matmul(tf.transpose(X),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 24],
       [43, 47]], dtype=int32)>

In [ ]:
#Try metrix multiplecation using tf.reshape
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[30, 31],
       [33, 33]], dtype=int32)>

## The dot product

Matrix Multiplecation aslo refered to as the dot product

You can perform matrix multiplecation
* 'tf.matmul()'
* 'tf.tensordot()'
* @ "python @ operator for multiplication"


In [ ]:
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[2, 5],
        [6, 7],
        [1, 8]], dtype=int32)>, <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [2, 3],
        [3, 2]], dtype=int32)>)

In [ ]:
tf.tensordot(tf.transpose(X),Y,axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[17, 24],
       [43, 47]], dtype=int32)>

In [ ]:
#Perform matrix multiplecation between X and Y(transpose)
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[12, 19, 16],
       [20, 33, 32],
       [17, 26, 19]], dtype=int32)>

In [ ]:
#Perform matrix multiplecation between X and Y(reshape)
tf.matmul(X, tf.reshape(Y, shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[17, 19, 14],
       [27, 33, 26],
       [25, 26, 18]], dtype=int32)>

In [ ]:
# Check the Values of Y, reshaped Y, transposed Y
print("Normal Y: ")
print(Y,"\n");

print("reshaped Y (2,3): ")
print(tf.reshape(Y,shape=(2,3)),"\n");

print("transposed Y: ")
print(tf.transpose(Y),"\n");


Normal Y: 
tf.Tensor(
[[1 2]
 [2 3]
 [3 2]], shape=(3, 2), dtype=int32) 

reshaped Y (2,3): 
tf.Tensor(
[[1 2 2]
 [3 3 2]], shape=(2, 3), dtype=int32) 

transposed Y: 
tf.Tensor(
[[1 2 3]
 [2 3 2]], shape=(2, 3), dtype=int32) 



## How to change a dataType of a tesnor


In [ ]:
#Create a tensor with float32

A= tf.constant([2.1,3.1])
A.dtype

tf.float32

In [ ]:
#Create a tensor with float32
B=tf.constant([2,3])
B.dtype

tf.int32

In [ ]:
#Chage dtype from float32 to float16 (reduced precision)
D=tf.cast(A, dtype=tf.float16)
D.dtype

tf.float16

In [ ]:
#Chage dtype from int32 to int16 (reduced precision)
E=tf.cast(B,dtype=tf.int16)
E.dtype

tf.int16

## Aggreigating tensors

* Aggregatting tensors means=considering them from multiple values down to a smaller amount of values 

In [ ]:
D =tf.constant([-7,-5])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 5], dtype=int32)>

### Let's gothrough following forms of aggregations

* Get the minimum
* Get the Maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
#Create a random tensor with values between 1 to 100 and sixe is 50

E= tf.constant(np.random.randint(0,100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([53, 78, 58, 10, 69, 66, 59, 36, 85, 61, 56, 12, 76, 69,  4, 40, 52,
       55, 10, 30, 35, 35, 11,  3, 86, 74, 85, 30, 19, 37, 51, 88, 39, 14,
       69, 73, 83, 66, 79, 52, 76, 82, 89, 54, 66, 71, 85, 18, 41,  2])>

In [ ]:
# Get the minimum of tensor 'E'
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Get the Maximum of tensor 'E'
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=89>

In [ ]:
# Get the mean of tensor 'E'
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
# Get the total of tensor 'E'
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2592>

## Find the "variance" and "standard deviation" of our tensor 'E'

In [ ]:
#Find out the "variance" and "standard deviation" of our tensor 'E'
tf.math.reduce_variance(tf.cast(E, dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=692.1344>

In [ ]:
#Find out the "standard deviation" of our tensor 'E'
tf.math.reduce_std(tf.cast(E, dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=26.308447>

##Find the positinal, maximum and minimum

In [ ]:
#Create a tensor to Find out the positional maximum and minimum
tf.random.set_seed(42)
F= tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
#Find the positional of maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
#Find out Index of our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
#Find out max value of our tensor
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
#Find the position of minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
#Find out mim value of our tensor
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

## Squeezing a tensor(Removing all single dimesions) 

In [ ]:
# Create a tensor
tf.random.set_seed(42)
G= tf.constant(tf.random.uniform(shape=[50]),shape=[1,1,1,1,50])
G, G.shape

(<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
 array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
            0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
            0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
            0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
            0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
            0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
            0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
            0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
       dtype=float32)>, TensorShape([1, 1, 1, 1, 50]))

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>, TensorShape([50]))

## One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0,1,2,3] # could be red, green, yellow, blue

#one-hot encoding of our list of indices
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values of one-hot encoding (on-value and off-value)
tf.one_hot(some_list, depth=4, on_value=5.0, off_value=0.0, axis=-1)


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]], dtype=float32)>

In [ ]:
indices = [0, 2, -1, 1]
depth = 3
tf.one_hot(indices, depth,
           on_value=5.0, off_value=0.0,
           axis=-1)  # output: [4 x 3]
# [[5.0, 0.0, 0.0],  # one_hot(0)
#  [0.0, 0.0, 5.0],  # one_hot(2)
#  [0.0, 0.0, 0.0],  # one_hot(-1)
#  [0.0, 5.0, 0.0]]  # one_hot(1)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[5., 0., 0.],
       [0., 0., 5.],
       [0., 0., 0.],
       [0., 5., 0.]], dtype=float32)>

## Squaring, log, square root

In [ ]:
#Create a tensor

H=tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
#Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
#Square root
tf.sqrt(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([1.   , 1.414, 1.732, 2.   , 2.236, 2.45 , 2.646, 2.828, 3.   ],
      dtype=float16)>

In [ ]:
#math log

tf.math.log(tf.cast(H, dtype=tf.float16))

<tf.Tensor: shape=(9,), dtype=float16, numpy=
array([0.    , 0.6934, 1.099 , 1.387 , 1.609 , 1.792 , 1.946 , 2.08  ,
       2.197 ], dtype=float16)>

## Tensors and NumPy

In [ ]:
#Create a tensor directly from a NumPy Array
J =tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
#Convert our tensor back to NumPy array

np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Conver J to NumPy array
J.numpy(), type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J=tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
#the default type of each are slightly different
numpy_J= tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
#Check each dtype 
numpy_J.dtype, tensor_J.dtype #(tf.float64, tf.float32)

(tf.float64, tf.float32)